---
# tasks file for koji-web

- name: Install | Install required Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - koji-web
    - mod_ssl
  tags:
    - koji-web
    - koji-web-package

- name: Configure /etc/kojiweb/web.conf
  template:
    src: web.conf.j2
    dest: /etc/kojiweb/web.conf
    owner: root
    group: root
    mode: 0644
  notify: httpd graceful
  tags:
    - koji-web-conf
    - koji-apache-conf
    - koji-web
    - koji-web-config

- include: check_certificates.yml
  vars:
    cert_file: "{{ item }}"
  with_items:
    - "{{ koji_web_apache_SSLCertificateFile }}"
    - "{{ koji_web_apache_SSLCertificateKeyFile }}"
    - "{{ koji_web_apache_SSLCertificateChainFile }}"
    - "{{ koji_web_apache_SSLCACertificateFile }}"
    - "{{ koji_web_WebCert }}"
    - "{{ koji_web_ClientCA }}"
    - "{{ koji_web_KojiHubCA }}"

- name: Configure /etc/httpd/conf.d/kojiweb.conf
  template:
    src: kojiweb.conf.j2
    dest: /etc/httpd/conf.d/kojiweb.conf
    owner: root
    group: root
    mode: 0644
  notify: httpd graceful
  tags:
    - koji-web-apache-conf
    - koji-apache-conf
    - koji-web
    - koji-web-config

- name: Configure /etc/httpd/conf.d/ssl.conf
  template:
    src: ssl.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf
    owner: root
    group: root
    mode: 0644
  when: koji_web_render_ssl_conf
  notify: httpd graceful
  tags:
    - koji-web
    - koji-web-ssl
    - koji-apache-conf
    - koji-apache-conf
    - koji-web-config

- name: issue cert for kojiweb
  shell: "{{ koji_web_ca_base_path }}/certgen.sh {{ item }}"
  args:
    creates: "{{ koji_web_ca_base_path }}/certs/{{ item }}.crt"
    chdir: "{{ koji_web_ca_base_path }}"
  with_items:
    - "{{ ansible_fqdn }}"
  when: koji_web_issue_cert

- name: "Ensure httpd is running"
  service: name=httpd state=started enabled=yes
  tags:
    - koji-web

